import DataFactory  from '../utilities/data-factory';
import TestRailMethods from '../utilities/testrail-factory';

class TestPlanSetUp {
   
  constructor(){

  }

  async isTestPlanAlreadyCreated(testPlanNameToCheck: any){
    const testrail = new TestRailMethods();
    return await testrail.isTestPlanCreated(testPlanNameToCheck);
  }

  async setupTestPlan(suiteId:any){
    const alltestcases = DataFactory.getAllTestCases();
    const listoftestcases = alltestcases.map((item: { TestcaseID: string; }) => parseInt(item.TestcaseID.replace('C', ''), 10));
    const testrail = new TestRailMethods();
    const testPlan = await testrail.createTestPlan("Regression Automation Playwright", "This is the suite generated by code");
    const testPlanId = await testPlan.id;
    const planEntry = await testrail.addTestSuiteToTestPlan(testPlanId, suiteId, listoftestcases);
    const testRunId = await planEntry.runs[0].id;
    return testRunId;
  }
}
export default TestPlanSetUp;
